# This file was generated by GoReleaser. DO NOT EDIT.
class GoGocd < Formula
  desc "CLI interface for ThoughtWorks GoCD"
  homepage "https://github.com/beamly/terraform-provider-gocd"
  version "0.7.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/beamly/go-gocd/releases/download/0.7.14/gocd-0.7.14-darwin-x86_64.zip"
    sha256 "2138401154d3b575e26f7145b76783997825286ec40ab9788c7a495c072d2a70"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/beamly/go-gocd/releases/download/0.7.14/gocd-0.7.14-linux-x86_64.tar.gz"
      sha256 "0600ad5d6662261f92a64a91e62d8bcf35718eb9963b5cb29503cdb6755a5d3c"
    end
  end
  
  depends_on "drewsonne/homebrew-tap/tf-install-provider"

  def install
    bin.install "gocd"
  end

  test do
    system "#{bin}/gocd --version"
  end
end
