# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderGocd < Formula
  desc "Terraform Provider for ThoughtWorks GoCD"
  homepage "https://github.com/beamly/terraform-provider-gocd"
  version "1.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/beamly/terraform-provider-gocd/releases/download/1.0.7/terraform-provider-gocd-1.0.7-darwin-amd64.zip"
    sha256 "8d3ba7eaf3b6b6b65acba5e30ef5602a813db6f1a58c8886707022e626658ee8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/beamly/terraform-provider-gocd/releases/download/1.0.7/terraform-provider-gocd-1.0.7-linux-amd64.tar.gz"
      sha256 "0a9effb289073462f24537061d0c373d7608b463a02f9889f556dea2c8653fac"
    end
  end
  
  depends_on "terraform"
  depends_on "drewsonne/homebrew-tap/tf-install-provider"

  def install
    bin.install "terraform-provider-gocd"
  end

  def caveats; <<~EOS
    After installing, you will need to copy the provider to a place terraform can find it by running:
      tf-install-provider artifactory
  EOS
  end

  test do
    system "#{bin}/terraform-provider-gocd; [[ $? -eq 1 ]]"
  end
end
