# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderGocd < Formula
  desc "Terraform Provider for ThoughtWorks GoCD"
  homepage "https://github.com/beamly/terraform-provider-gocd"
  version "1.0.4"

  if OS.mac?
    url "https://github.com/beamly/terraform-provider-gocd/releases/download/1.0.4/terraform-provider-gocd-1.0.4-darwin-amd64.zip"
    sha256 "9bcbc35eb9f441b4d9ddb5fd076cad48d9c80890d8cc2c790674a8b2b27971ed"
  elsif OS.linux?
    url "https://github.com/beamly/terraform-provider-gocd/releases/download/1.0.4/terraform-provider-gocd-1.0.4-linux-amd64.tar.gz"
    sha256 "1ef33ddc2d5917a4775f22c06ed5c97ca49424ae39cc069803162fa9807232fd"
  end
  
  depends_on "terraform"
  depends_on "drewsonne/homebrew-tap/tf-install-provider"

  def install
    bin.install "terraform-provider-gocd"
  end

  def caveats; <<~EOS
    After installing, you will need to copy the provider to a place terraform can find it by running:
      tf-install-provider artifactory
  EOS
  end

  test do
    system "#{bin}/terraform-provider-gocd; [[ $? -eq 1 ]]"
  end
end
