# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderGocd < Formula
  desc "Terraform Provider for ThoughtWorks GoCD"
  homepage "https://github.com/beamly/terraform-provider-gocd"
  version "1.0.18"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/beamly/terraform-provider-gocd/releases/download/1.0.18/terraform-provider-gocd-1.0.18-darwin-amd64.zip"
    sha256 "c407c9506566d3eff216de956016da2c59dcff76fd022552d6770710039ea061"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/beamly/terraform-provider-gocd/releases/download/1.0.18/terraform-provider-gocd-1.0.18-linux-amd64.tar.gz"
      sha256 "f1b29662f3cbad50a66ce660404f843bb0def2ff0640e0d8c16a50ea2894f395"
    end
  end
  
  depends_on "terraform"
  depends_on "drewsonne/homebrew-tap/tf-install-provider"

  def install
    bin.install "terraform-provider-gocd"
  end

  def caveats; <<~EOS
    After installing, you will need to copy the provider to a place terraform can find it by running:
      tf-install-provider artifactory
  EOS
  end

  test do
    system "#{bin}/terraform-provider-gocd; [[ $? -eq 1 ]]"
  end
end
